services:
  website:
    image: ghcr.io/alpsify/lychen/staging/vara/website:latest
    labels:
      - traefik.http.routers.lychen-staging-vara-website-dwk8po-74-websecure.middlewares=ip-allow@file
    restart: unless-stopped
