services:
  website:
    image: ghcr.io/alpsify/lychen/staging/kiro/website:latest
    labels:
      - traefik.http.routers.lychen-staging-kiro-website-xvqpgr-76-websecure.middlewares=ip-allow@file
    restart: unless-stopped
