import fs from 'fs/promises';
import path from 'path';

async function generateIndex() {
  const generatedDir = path.resolve('./generated'); // Relative to this script's location
  const indexFilePath = path.join(generatedDir, 'index.ts');

  try {
    const files = await fs.readdir(generatedDir);
    const apiFiles = files.filter(
      (file) =>
        file.endsWith('.ts') &&
        file !== 'index.ts' &&
        file !== 'http-client.ts' &&
        file !== 'data-contracts.ts', // Exclude data-contracts.ts from re-export
    );

    // Removed the httpClientFile check because we don't need it anymore in this file.
    let indexContent = `// This file is automatically generated. Do not edit it directly.\n\n`; // Remove reexport of http-client

    for (const file of apiFiles) {
      const className = path.basename(file, '.ts');
      indexContent += `export * from './${className}';\n`;
    }

    await fs.writeFile(indexFilePath, indexContent, 'utf-8');

    console.log(`Successfully generated index.ts in ${generatedDir}`);
  } catch (error) {
    console.error('Error generating index.ts:', error);
    process.exit(1); // Exit with an error code
  }
}

generateIndex();
