enableImmutableInstalls: false

nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: '${FONTAWESOME_PACKAGE_TOKEN}'
    npmRegistryServer: 'https://npm.fontawesome.com/'
