nodeLinker: node-modules

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.fontawesome.com/"
    #npmAuthToken: ${FONTAWESOME_PACKAGE_TOKEN}

yarnPath: .yarn/releases/yarn-4.5.1.cjs
