snc_redis:
  doctrine:
    metadata_cache:
      client: doctrine_metadata_cache
      entity_manager: default
      document_manager: default
    result_cache:
      client: doctrine_metadata_cache
      entity_manager: default
    query_cache:
      client: doctrine_metadata_cache
      entity_manager: default
