services:
  website:
    image: ghcr.io/alpsify/lychen/staging/eko/website:latest
    labels:
      - traefik.http.routers.lychen-staging-eko-website-wtuu4x-70-websecure.middlewares=ip-allow@file
    restart: unless-stopped
