name: common

services:
  mailpit:
    environment:
      MP_DATABASE: /data/mailpit.db
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - mailpit_data:/data

volumes:
  mailpit_data:
