framework:
  workflows:
    !php/const App\Workflow\LandTask\LandTaskWorkflow::NAME:
      audit_trail:
        enabled: true
      initial_marking: !php/const App\Workflow\LandTask\LandTaskWorkflowPlace::TO_BE_DONE
      marking_store:
        property: 'state'
        type: 'method'
      places: !php/const App\Workflow\LandTask\LandTaskWorkflowPlace::PLACES
      supports:
        - App\Entity\LandTask
      transitions:
        !php/const App\Workflow\LandTask\LandTaskWorkflowTransition::MARK_AS_IN_PROGRESS:
          from: !php/const App\Workflow\LandTask\LandTaskWorkflowPlace::TO_BE_DONE
          to: !php/const App\Workflow\LandTask\LandTaskWorkflowPlace::IN_PROGRESS
        !php/const App\Workflow\LandTask\LandTaskWorkflowTransition::MARK_AS_DONE:
          from:
            - !php/const App\Workflow\LandTask\LandTaskWorkflowPlace::TO_BE_DONE
            - !php/const App\Workflow\LandTask\LandTaskWorkflowPlace::IN_PROGRESS
          to: !php/const App\Workflow\LandTask\LandTaskWorkflowPlace::DONE
      type: 'state_machine'
