framework:
  workflows:
    !php/const App\Workflow\LandProposal\LandProposalWorkflow::NAME:
      audit_trail:
        enabled: true
      initial_marking: !php/const App\Workflow\LandProposal\LandProposalWorkflowPlace::DRAFT
      marking_store:
        property: 'state'
        type: 'method'
      places: !php/const App\Workflow\LandProposal\LandProposalWorkflowPlace::PLACES
      supports:
        - App\Entity\LandProposal
      transitions:
        !php/const App\Workflow\LandProposal\LandProposalWorkflowTransition::PUBLISH:
          from: !php/const App\Workflow\LandProposal\LandProposalWorkflowPlace::DRAFT
          to: !php/const App\Workflow\LandProposal\LandProposalWorkflowPlace::PUBLISHED
        !php/const App\Workflow\LandProposal\LandProposalWorkflowTransition::ARCHIVE:
          from: !php/const App\Workflow\LandProposal\LandProposalWorkflowPlace::PUBLISHED
          to: !php/const App\Workflow\LandProposal\LandProposalWorkflowPlace::ARCHIVED
      type: 'state_machine'
