framework:
  workflows:
    !php/const App\Workflow\LandMemberInvitation\LandMemberInvitationWorkflow::NAME:
      audit_trail:
        enabled: true
      initial_marking: !php/const App\Workflow\LandMemberInvitation\LandMemberInvitationWorkflowPlace::PENDING
      marking_store:
        property: 'state'
        type: 'method'
      places: !php/const App\Workflow\LandMemberInvitation\LandMemberInvitationWorkflowPlace::PLACES
      supports:
        - App\Entity\LandMemberInvitation
      transitions:
        !php/const App\Workflow\LandMemberInvitation\LandMemberInvitationWorkflowTransition::ACCEPT:
          from: !php/const App\Workflow\LandMemberInvitation\LandMemberInvitationWorkflowPlace::PENDING
          to: !php/const App\Workflow\LandMemberInvitation\LandMemberInvitationWorkflowPlace::ACCEPTED
        !php/const App\Workflow\LandMemberInvitation\LandMemberInvitationWorkflowTransition::REFUSE:
          from: !php/const App\Workflow\LandMemberInvitation\LandMemberInvitationWorkflowPlace::PENDING
          to: !php/const App\Workflow\LandMemberInvitation\LandMemberInvitationWorkflowPlace::REFUSED
      type: 'state_machine'
