framework:
  workflows:
    land_area:
      audit_trail:
        enabled: true
      initial_marking: !php/const App\Workflow\LandArea\LandAreaWorkflowPlace::ACTIVE
      marking_store:
        property: 'state'
        type: 'method'
      places: !php/const App\Workflow\LandArea\LandAreaWorkflowPlace::PLACES
      supports:
        - App\Entity\LandArea
      transitions:
        !php/const App\Workflow\LandArea\LandAreaWorkflowTransition::ARCHIVE:
          from: !php/const App\Workflow\LandArea\LandAreaWorkflowPlace::ACTIVE
          to: !php/const App\Workflow\LandArea\LandAreaWorkflowPlace::ARCHIVED
      type: 'state_machine'
