framework:
  workflows:
    land_request:
      audit_trail:
        enabled: true
      initial_marking: !php/const App\Workflow\LandRequest\LandRequestWorkflowPlace::DRAFT
      marking_store:
        property: 'state'
        type: 'method'
      places: !php/const App\Workflow\LandRequest\LandRequestWorkflowPlace::PLACES
      supports:
        - App\Entity\LandRequest
      transitions:
        !php/const App\Workflow\LandRequest\LandRequestWorkflowTransition::PUBLISH:
          from: !php/const App\Workflow\LandRequest\LandRequestWorkflowPlace::DRAFT
          to: !php/const App\Workflow\LandRequest\LandRequestWorkflowPlace::PUBLISHED
        !php/const App\Workflow\LandRequest\LandRequestWorkflowTransition::ARCHIVE:
          from: !php/const App\Workflow\LandRequest\LandRequestWorkflowPlace::PUBLISHED
          to: !php/const App\Workflow\LandRequest\LandRequestWorkflowPlace::ARCHIVED
      type: 'state_machine'
