framework:
  workflows:
    land_deal:
      audit_trail:
        enabled: true
      initial_marking: !php/const App\Workflow\LandDeal\LandDealWorkflowPlace::OPENED
      marking_store:
        property: 'state'
        type: 'method'
      places: !php/const App\Workflow\LandDeal\LandDealWorkflowPlace::PLACES
      supports:
        - App\Entity\LandDeal
      transitions:
        !php/const App\Workflow\LandDeal\LandDealWorkflowTransition::ACCEPT:
          from: !php/const App\Workflow\LandDeal\LandDealWorkflowPlace::OPENED
          to: !php/const App\Workflow\LandDeal\LandDealWorkflowPlace::ACCEPTED
        !php/const App\Workflow\LandDeal\LandDealWorkflowTransition::ARCHIVE:
          from:
            - !php/const App\Workflow\LandDeal\LandDealWorkflowPlace::OPENED
            - !php/const App\Workflow\LandDeal\LandDealWorkflowPlace::ACCEPTED
            - !php/const App\Workflow\LandDeal\LandDealWorkflowPlace::REFUSED
          to: !php/const App\Workflow\LandDeal\LandDealWorkflowPlace::ARCHIVED
        !php/const App\Workflow\LandDeal\LandDealWorkflowTransition::REFUSE:
          from: !php/const App\Workflow\LandDeal\LandDealWorkflowPlace::OPENED
          to: !php/const App\Workflow\LandDeal\LandDealWorkflowPlace::REFUSED
      type: 'state_machine'
