services:
  app:
    image: ghcr.io/lychen-lab/lychen/staging/tera/app:latest
    #labels:
    # - traefik.http.routers.lychen-staging-tera-app-qpolyk-115-websecure.middlewares=ip-allow@file
    restart: unless-stopped
