name: common

services:
  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_VHOST=common
    image: rabbitmq:4.0.4-management-alpine
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_config:/etc/rabbitmq/
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  rabbitmq_data:
  rabbitmq_config:
