services:
  php:
    env_file:
      - .env
    image: wrong #TODO To change
    ports:
      - protocol: tcp
        published: ${HTTP_PORT:-80}
        target: 80
      - protocol: tcp
        published: ${HTTPS_PORT:-443}
        target: 443
      - protocol: udp
        published: ${HTTP3_PORT:-443}
        target: 443
    restart: unless-stopped
    volumes:
      - 'caddy_data:/data'
      - 'caddy_config:/config'
      - 'api_logs:/app/var/log'
      - '../files/jwt:/app/config/jwt'
      
volumes:
  caddy_config:
  caddy_data:
