services:
  php:
    image: wrong #TODO To change
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - 'caddy_data:/data'
      - 'caddy_config:/config'
      - 'api_logs:/app/var/log'
      - '../files/jwt:/app/config/jwt'
    ports:
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

volumes:
  caddy_data:
  caddy_config:
