services:
  api:
    image: ghcr.io/alpsify/lychen/staging/tera/api:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - 'caddy_data:/data'
      - 'caddy_config:/config'
      - 'api_logs:/app/var/log'
    expose:
      - 80

volumes:
  caddy_data: null
  caddy_config: null
  api_logs: null
