services:
  website:
    image: ghcr.io/alpsify/lychen/staging/website:latest
    labels:
      - traefik.http.routers.lychen-staging-website-bbfdnf-61-websecure.middlewares=ip-allow@file
    restart: unless-stopped
