<?php

declare(strict_types=1);

namespace DoctrineDefaultMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250802082723 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cultivation (sowing_minimal_temperature INT DEFAULT NULL, sowing_optimal_temperature INT DEFAULT NULL, planting_spacing INT DEFAULT NULL, minimal_days_to_harvest INT DEFAULT NULL, maximal_days_to_harvest INT DEFAULT NULL, vegetation_temperature_threshold INT NOT NULL, days_to_germination_average INT DEFAULT NULL, sowing_months JSONB DEFAULT NULL, harvesting_months JSONB DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ACAFA797C288C859 ON cultivation (ulid)');
        $this->addSql('CREATE TABLE family (code VARCHAR(100) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A5E6215B77153098 ON family (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A5E6215BC288C859 ON family (ulid)');
        $this->addSql('CREATE TABLE lunar_type (code VARCHAR(100) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2BF6832F77153098 ON lunar_type (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2BF6832FC288C859 ON lunar_type (ulid)');
        $this->addSql('CREATE TABLE maturity (code VARCHAR(100) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4636E0E877153098 ON maturity (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4636E0E8C288C859 ON maturity (ulid)');
        $this->addSql('CREATE TABLE species (code VARCHAR(100) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A50FF71277153098 ON species (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A50FF712C288C859 ON species (ulid)');
        $this->addSql('ALTER TABLE plant ADD perennial BOOLEAN NOT NULL');
        $this->addSql('ALTER TABLE plant ADD name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE plant ADD scientific_name VARCHAR(255) NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE cultivation');
        $this->addSql('DROP TABLE family');
        $this->addSql('DROP TABLE lunar_type');
        $this->addSql('DROP TABLE maturity');
        $this->addSql('DROP TABLE species');
        $this->addSql('ALTER TABLE plant DROP perennial');
        $this->addSql('ALTER TABLE plant DROP name');
        $this->addSql('ALTER TABLE plant DROP scientific_name');
    }
}
