<?php

declare(strict_types=1);

namespace DoctrineDefaultMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250802170330 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE plant_part (consumable BOOLEAN NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, plant_id INT NOT NULL, part_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2AE7B0D4C288C859 ON plant_part (ulid)');
        $this->addSql('CREATE INDEX IDX_2AE7B0D41D935652 ON plant_part (plant_id)');
        $this->addSql('CREATE INDEX IDX_2AE7B0D44CE34BEC ON plant_part (part_id)');
        $this->addSql('ALTER TABLE plant_part ADD CONSTRAINT FK_2AE7B0D41D935652 FOREIGN KEY (plant_id) REFERENCES plant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE plant_part ADD CONSTRAINT FK_2AE7B0D44CE34BEC FOREIGN KEY (part_id) REFERENCES part (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE plant_part DROP CONSTRAINT FK_2AE7B0D41D935652');
        $this->addSql('ALTER TABLE plant_part DROP CONSTRAINT FK_2AE7B0D44CE34BEC');
        $this->addSql('DROP TABLE plant_part');
    }
}
