<?php

declare(strict_types=1);

namespace DoctrineDefaultMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250803151505 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE consumption_method (code VARCHAR(100) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CD3E630B77153098 ON consumption_method (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CD3E630BC288C859 ON consumption_method (ulid)');
        $this->addSql('CREATE TABLE cultivation (sowing_minimal_temperature INT DEFAULT NULL, sowing_maximal_temperature INT DEFAULT NULL, planting_spacing INT DEFAULT NULL, minimal_days_to_harvest INT DEFAULT NULL, maximal_days_to_harvest INT DEFAULT NULL, vegetation_temperature_threshold INT DEFAULT NULL, sowing_months JSONB DEFAULT NULL, harvesting_months JSONB DEFAULT NULL, minimal_days_to_germination INT DEFAULT NULL, maximal_days_to_germination INT DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, maturity_id INT NOT NULL, exposure_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ACAFA797C288C859 ON cultivation (ulid)');
        $this->addSql('CREATE INDEX IDX_ACAFA7975074221B ON cultivation (maturity_id)');
        $this->addSql('CREATE INDEX IDX_ACAFA797C677C140 ON cultivation (exposure_id)');
        $this->addSql('CREATE TABLE exposure (code VARCHAR(100) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_398F29CD77153098 ON exposure (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_398F29CDC288C859 ON exposure (ulid)');
        $this->addSql('CREATE TABLE family (code VARCHAR(100) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A5E6215B77153098 ON family (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A5E6215BC288C859 ON family (ulid)');
        $this->addSql('CREATE TABLE lunar_type (code VARCHAR(100) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2BF6832F77153098 ON lunar_type (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2BF6832FC288C859 ON lunar_type (ulid)');
        $this->addSql('CREATE TABLE maturity (code VARCHAR(100) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4636E0E877153098 ON maturity (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4636E0E8C288C859 ON maturity (ulid)');
        $this->addSql('CREATE TABLE part (code VARCHAR(100) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_490F70C677153098 ON part (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_490F70C6C288C859 ON part (ulid)');
        $this->addSql('CREATE TABLE plant (perennial BOOLEAN NOT NULL, name VARCHAR(255) NOT NULL, melliferous BOOLEAN NOT NULL, medicinal BOOLEAN NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, lunar_type_id INT DEFAULT NULL, species_id INT NOT NULL, cultivation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AB030D72C288C859 ON plant (ulid)');
        $this->addSql('CREATE INDEX IDX_AB030D7211205867 ON plant (lunar_type_id)');
        $this->addSql('CREATE INDEX IDX_AB030D72B2A1D860 ON plant (species_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AB030D723932FFBE ON plant (cultivation_id)');
        $this->addSql('CREATE TABLE plant_soil_type (plant_id INT NOT NULL, soil_type_id INT NOT NULL, PRIMARY KEY (plant_id, soil_type_id))');
        $this->addSql('CREATE INDEX IDX_D561DC091D935652 ON plant_soil_type (plant_id)');
        $this->addSql('CREATE INDEX IDX_D561DC09A8AE1818 ON plant_soil_type (soil_type_id)');
        $this->addSql('CREATE TABLE plant_part (consumable BOOLEAN NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, plant_id INT NOT NULL, part_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2AE7B0D4C288C859 ON plant_part (ulid)');
        $this->addSql('CREATE INDEX IDX_2AE7B0D41D935652 ON plant_part (plant_id)');
        $this->addSql('CREATE INDEX IDX_2AE7B0D44CE34BEC ON plant_part (part_id)');
        $this->addSql('CREATE TABLE plant_part_consumption_method (plant_part_id INT NOT NULL, consumption_method_id INT NOT NULL, PRIMARY KEY (plant_part_id, consumption_method_id))');
        $this->addSql('CREATE INDEX IDX_97320500366A8195 ON plant_part_consumption_method (plant_part_id)');
        $this->addSql('CREATE INDEX IDX_97320500E5A50FD3 ON plant_part_consumption_method (consumption_method_id)');
        $this->addSql('CREATE TABLE soil_type (code VARCHAR(100) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_502D4F9177153098 ON soil_type (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_502D4F91C288C859 ON soil_type (ulid)');
        $this->addSql('CREATE TABLE species (code VARCHAR(100) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, family_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A50FF71277153098 ON species (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A50FF712C288C859 ON species (ulid)');
        $this->addSql('CREATE INDEX IDX_A50FF712C35E566A ON species (family_id)');
        $this->addSql('ALTER TABLE cultivation ADD CONSTRAINT FK_ACAFA7975074221B FOREIGN KEY (maturity_id) REFERENCES maturity (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cultivation ADD CONSTRAINT FK_ACAFA797C677C140 FOREIGN KEY (exposure_id) REFERENCES exposure (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE plant ADD CONSTRAINT FK_AB030D7211205867 FOREIGN KEY (lunar_type_id) REFERENCES lunar_type (id)');
        $this->addSql('ALTER TABLE plant ADD CONSTRAINT FK_AB030D72B2A1D860 FOREIGN KEY (species_id) REFERENCES species (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE plant ADD CONSTRAINT FK_AB030D723932FFBE FOREIGN KEY (cultivation_id) REFERENCES cultivation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE plant_soil_type ADD CONSTRAINT FK_D561DC091D935652 FOREIGN KEY (plant_id) REFERENCES plant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE plant_soil_type ADD CONSTRAINT FK_D561DC09A8AE1818 FOREIGN KEY (soil_type_id) REFERENCES soil_type (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE plant_part ADD CONSTRAINT FK_2AE7B0D41D935652 FOREIGN KEY (plant_id) REFERENCES plant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE plant_part ADD CONSTRAINT FK_2AE7B0D44CE34BEC FOREIGN KEY (part_id) REFERENCES part (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE plant_part_consumption_method ADD CONSTRAINT FK_97320500366A8195 FOREIGN KEY (plant_part_id) REFERENCES plant_part (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE plant_part_consumption_method ADD CONSTRAINT FK_97320500E5A50FD3 FOREIGN KEY (consumption_method_id) REFERENCES consumption_method (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE species ADD CONSTRAINT FK_A50FF712C35E566A FOREIGN KEY (family_id) REFERENCES family (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cultivation DROP CONSTRAINT FK_ACAFA7975074221B');
        $this->addSql('ALTER TABLE cultivation DROP CONSTRAINT FK_ACAFA797C677C140');
        $this->addSql('ALTER TABLE plant DROP CONSTRAINT FK_AB030D7211205867');
        $this->addSql('ALTER TABLE plant DROP CONSTRAINT FK_AB030D72B2A1D860');
        $this->addSql('ALTER TABLE plant DROP CONSTRAINT FK_AB030D723932FFBE');
        $this->addSql('ALTER TABLE plant_soil_type DROP CONSTRAINT FK_D561DC091D935652');
        $this->addSql('ALTER TABLE plant_soil_type DROP CONSTRAINT FK_D561DC09A8AE1818');
        $this->addSql('ALTER TABLE plant_part DROP CONSTRAINT FK_2AE7B0D41D935652');
        $this->addSql('ALTER TABLE plant_part DROP CONSTRAINT FK_2AE7B0D44CE34BEC');
        $this->addSql('ALTER TABLE plant_part_consumption_method DROP CONSTRAINT FK_97320500366A8195');
        $this->addSql('ALTER TABLE plant_part_consumption_method DROP CONSTRAINT FK_97320500E5A50FD3');
        $this->addSql('ALTER TABLE species DROP CONSTRAINT FK_A50FF712C35E566A');
        $this->addSql('DROP TABLE consumption_method');
        $this->addSql('DROP TABLE cultivation');
        $this->addSql('DROP TABLE exposure');
        $this->addSql('DROP TABLE family');
        $this->addSql('DROP TABLE lunar_type');
        $this->addSql('DROP TABLE maturity');
        $this->addSql('DROP TABLE part');
        $this->addSql('DROP TABLE plant');
        $this->addSql('DROP TABLE plant_soil_type');
        $this->addSql('DROP TABLE plant_part');
        $this->addSql('DROP TABLE plant_part_consumption_method');
        $this->addSql('DROP TABLE soil_type');
        $this->addSql('DROP TABLE species');
    }
}
