doctrine_migrations:
  # Run all migrations in a transaction.
  all_or_nothing: false
  # Path to your custom migrations template
  custom_template: ~

  migrations_paths:
    DoctrineDefaultMigrations: '%kernel.project_dir%/migrations'

  # Possible values: "BY_YEAR", "BY_YEAR_AND_MONTH", false
  organize_migrations: false
  services:
    Doctrine\Migrations\Version\MigrationFactory: App\Migrations\Factory\MigrationFactoryDecorator

  storage:
    # Default (SQL table) metadata storage configuration
    table_storage:
      executed_at_column_name: 'executed_at'

      table_name: 'doctrine_migration_versions'
      version_column_length: 191
      version_column_name: 'version'
