security:
  access_control:
    - { path: ^/api/docs, roles: PUBLIC_ACCESS }
    - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      custom_authenticators:
        - Lychen\UtilZitadelBundle\Authenticator\ZitadelUserAuthenticator
      lazy: true
      pattern: ^/
      provider: zitadel_user_provider
      stateless: true

  providers:
    zitadel_user_provider:
      id: Lychen\UtilZitadelBundle\UserProvider\ZitadelUserProvider
