security:
  access_control:
    - { path: ^/api/docs, roles: PUBLIC_ACCESS }

  #access_decision_manager:
    #allow_if_all_abstain: false
    #strategy: unanimous

  firewalls:
    main:
      pattern: ^/
      provider: zitadel_user_provider
      stateless: true
      custom_authenticators:
        - App\Security\ZitadelUserAuthenticator

    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

  providers:
    zitadel_user_provider:
      id: App\Security\ZitadelUserProvider

