security:
  access_control:
    - { path: ^/api/docs, roles: PUBLIC_ACCESS }

  #access_decision_manager:
    #allow_if_all_abstain: false
    #strategy: unanimous

  firewalls:
    main:
      pattern: ^/
      provider: user_provider
      stateless: true
      custom_authenticators:
        - App\Security\ZitadelUserAuthenticator

    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

  providers:
    user_provider:
      entity:
        class: 'App/Entity/User'
        property: 'authId'

