security:
  access_control:
    - { path: ^/api/docs, roles: PUBLIC_ACCESS }
    - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }

  firewalls:
    main:
      pattern: ^/
      lazy: true
      provider: zitadel_user_provider
      stateless: true
      custom_authenticators:
        - App\Security\ZitadelUserAuthenticator

    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

  providers:
    zitadel_user_provider:
      id: App\Security\ZitadelUserProvider
