when@prod:
  monolog:
    handlers:
      sentry:
        fill_extra_context: true
        hub_id: Sentry\State\HubInterface
        level: !php/const Monolog\Logger::ERROR
        type: sentry
  sentry:
    dsn: '%env(SENTRY_DSN)%'
    register_error_handler: false
    #        If you are using Monolog, you also need these additional configuration and services to log the errors correctly:
    #        https://docs.sentry.io/platforms/php/guides/symfony/#monolog-integration
    register_error_listener: false
