$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  assets-sync:
    command: noop
    deps:
      - args: '$projectRoot/public/fonts'
        target: assets-fonts:create-symlink-on-content

  build:
    command: yarn build
    deps:
      - assets-sync
    options:
      cache: false

  dev:
    command: yarn run dev
    deps:
      - assets-sync
    env:
      VITE_UNHEAD_HOST: ${DEV_DOMAIN}
    options:
      persistent: true

  production-build:
    args:
      - '--mode production'
    env:
      VITE_UNHEAD_HOST: ${PRODUCTION_DOMAIN}
    extends: build

  staging-build:
    args:
      - '--mode staging'
    env:
      VITE_UNHEAD_HOST: ${STAGING_DOMAIN}
    extends: build
