$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  format-fix:
    command:
      - prettier
      - --write
      - --no-error-on-unmatched-pattern
      - .
    inputs:
      - '**/*.{vue,ts,js,yaml,yml,json}'
      - '!**/build/'
      - '!**/dist/'
      - '!**/playwright-report/'

  lint-fix:
    command:
      - eslint
      - --fix
      - --report-unused-disable-directives
      - --no-error-on-unmatched-pattern
      - --exit-on-fatal-error
      - .
    inputs:
      - '**/*.{vue,ts,js,yaml,yml,json}'
      - '!**/build/'
      - '!**/dist/'
      - '!**/playwright-report/'
