$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  assets-sync:
    command: noop
    deps:
      - sync-fonts
      - sync-logos

  dev:
    command: yarn run dev
    deps:
      - assets-sync
    options:
      persistent: true

  production-build:
    command: yarn run build
    deps:
      - assets-sync
      - ^:affected
    options:
      cache: false

  staging-build:
    command: yarn run build
    deps:
      - assets-sync
      - ^:affected
    options:
      cache: false

  sync-fonts:
    command: ln -sfn $workspaceRoot/libs/assets/fonts $projectRoot/public/fonts
    deps:
      - assets:affected
    inputs:
      - '/libs/assets/fonts/**/*'
    options:
      cache: false
    platform: system

  sync-logos:
    command: ln -sfn $workspaceRoot/libs/assets/logos $projectRoot/public/logos
    deps:
      - assets:affected
    inputs:
      - '/libs/assets/logos/**/*'
    options:
      cache: false
    platform: system
