$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  build:
    command: yarn run build
    deps:
      - sync-logos
      - sync-fonts

  dev:
    command: yarn run dev
    deps:
      - sync-logos
      - sync-fonts
    options:
      persistent: true

  sync-fonts:
    command: ln -sfn $workspaceRoot/libs/assets/fonts $projectRoot/public/fonts
    inputs:
      - '/libs/assets/fonts/**/*'
    options:
      cache: false
    platform: system

  sync-logos:
    command: ln -sfn $workspaceRoot/libs/assets/logos $projectRoot/public/logos
    inputs:
      - '/libs/assets/logos/**/*'
    options:
      cache: false
    platform: system
