$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  bash-php:
    command: docker compose exec php bash
    options:
      persistent: true

  dev:
    command: docker compose up -d

  docker-build:
    command: docker build $projectRoot --cache-from ${DOCKER_IMAGE_NAME}:latest --platform linux/arm64,linux/amd64 --target frankenphp_prod -t ${DOCKER_IMAGE_NAME}:latest
    options:
      cache: false

  docker-push:
    command: docker push
    options:
      cache: false

  down:
    command: docker compose down --remove-orphans

  production-docker-build:
    env:
      DOCKER_IMAGE_NAME: 'ghcr.io/alpsify/${PRODUCTION_DOCKER_IMAGE}'
    extends: docker-build

  production-docker-push:
    args:
      - 'ghcr.io/alpsify/${PRODUCTION_DOCKER_IMAGE}'
    deps:
      - production-docker-build
    extends: docker-push

  staging-docker-build:
    env:
      DOCKER_IMAGE_NAME: 'ghcr.io/alpsify/${STAGING_DOCKER_IMAGE}'
    extends: docker-build

  staging-docker-push:
    args:
      - 'ghcr.io/alpsify/${STAGING_DOCKER_IMAGE}'
    deps:
      - staging-docker-build
    extends: docker-push
