$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  docker-build:
    command: docker build $projectRoot --no-cache -t
    options:
      cache: false

  docker-push:
    command: docker push
    options:
      cache: false

  production-docker-build:
    args:
      - 'ghcr.io/lychen-lab/${PRODUCTION_DOCKER_IMAGE}:latest'
    deps:
      - production-build
    extends: docker-build

  production-docker-push:
    args:
      - 'ghcr.io/lychen-lab/${PRODUCTION_DOCKER_IMAGE}:latest'
    deps:
      - production-docker-build
    extends: docker-push

  staging-docker-build:
    args:
      - 'ghcr.io/lychen-lab/${STAGING_DOCKER_IMAGE}:latest'
    deps:
      - staging-build
    extends: docker-build

  staging-docker-push:
    args:
      - 'ghcr.io/lychen-lab/${STAGING_DOCKER_IMAGE}:latest'
    deps:
      - staging-docker-build
    extends: docker-push
