$schema: 'https://moonrepo.dev/schemas/tasks.json'

tasks:
  build:
    command: yarn build
    deps:
      - assets-sync
      - args: $projectRoot/.nginx-build
        target: nginx-configs:sync-pwa
    options:
      cache: false

  generate-pwa-assets:
    command: yarn generate-pwa-assets
    deps:
      - assets-sync
