<?php

declare(strict_types=1);

namespace DoctrineDefaultMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250727155550 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE land_harvest_entry (weight INT NOT NULL, notes JSON DEFAULT NULL, harvested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, quality VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, land_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_4EBD87CBC288C859 ON land_harvest_entry (ulid)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_4EBD87CB1994904A ON land_harvest_entry (land_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_harvest_entry ADD CONSTRAINT FK_4EBD87CB1994904A FOREIGN KEY (land_id) REFERENCES land (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE land_harvest_entry DROP CONSTRAINT FK_4EBD87CB1994904A
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE land_harvest_entry
        SQL);
    }
}
