<?php

declare(strict_types=1);

namespace DoctrineDefaultMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250411072755 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE land_deal (state VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, land_id INT NOT NULL, person_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_700AFADFC288C859 ON land_deal (ulid)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_700AFADF1994904A ON land_deal (land_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_700AFADF217BBB47 ON land_deal (person_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE land_proposal (title VARCHAR(255) NOT NULL, description JSON DEFAULT NULL, soil_type VARCHAR(255) NOT NULL, orientation VARCHAR(255) NOT NULL, has_parking BOOLEAN NOT NULL, has_tools BOOLEAN NOT NULL, has_shed BOOLEAN NOT NULL, has_water_point BOOLEAN NOT NULL, has_independent_access BOOLEAN NOT NULL, garden_state VARCHAR(255) NOT NULL, gardening_preference VARCHAR(255) NOT NULL, gardening_level VARCHAR(255) NOT NULL, looking_for_gardener_level VARCHAR(255) NOT NULL, garden_total_surface INT NOT NULL, food_security_participation BOOLEAN NOT NULL, state VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, land_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_8548D9C8C288C859 ON land_proposal (ulid)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8548D9C81994904A ON land_proposal (land_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE land_request (state VARCHAR(255) NOT NULL, message JSON DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, person_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_238BFBFEC288C859 ON land_request (ulid)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_238BFBFE217BBB47 ON land_request (person_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_deal ADD CONSTRAINT FK_700AFADF1994904A FOREIGN KEY (land_id) REFERENCES land (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_deal ADD CONSTRAINT FK_700AFADF217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_proposal ADD CONSTRAINT FK_8548D9C81994904A FOREIGN KEY (land_id) REFERENCES land (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_request ADD CONSTRAINT FK_238BFBFE217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_research_request DROP CONSTRAINT fk_8ec04344217bbb47
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE land_research_deal
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE land_research_request
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE land_research_deal (state VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_714e71d9c288c859 ON land_research_deal (ulid)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE land_research_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, person_id INT NOT NULL, state VARCHAR(255) NOT NULL, message JSON DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_8ec04344217bbb47 ON land_research_request (person_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_8ec04344c288c859 ON land_research_request (ulid)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_research_request ADD CONSTRAINT fk_8ec04344217bbb47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_deal DROP CONSTRAINT FK_700AFADF1994904A
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_deal DROP CONSTRAINT FK_700AFADF217BBB47
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_proposal DROP CONSTRAINT FK_8548D9C81994904A
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_request DROP CONSTRAINT FK_238BFBFE217BBB47
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE land_deal
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE land_proposal
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE land_request
        SQL);
    }
}
