<?php

declare(strict_types=1);

namespace DoctrineDefaultMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250411090651 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE address (street_line VARCHAR(255) DEFAULT NULL, postal_code VARCHAR(20) DEFAULT NULL, country_code VARCHAR(2) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_D4E6F81C288C859 ON address (ulid)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land ADD address_id INT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land ADD CONSTRAINT FK_A800D5D8F5B7AF75 FOREIGN KEY (address_id) REFERENCES address (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_A800D5D8F5B7AF75 ON land (address_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_proposal ADD preferred_garden_interaction_mode VARCHAR(30) NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_proposal ADD sharing_conditions TEXT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_proposal DROP gardening_preference
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_proposal ALTER soil_type TYPE VARCHAR(20)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_proposal ALTER orientation TYPE VARCHAR(20)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_proposal ALTER gardening_level TYPE VARCHAR(30)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_proposal ALTER looking_for_gardener_level TYPE VARCHAR(30)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_request ADD minimum_surface_wanted INT DEFAULT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_request ADD gardening_level VARCHAR(30) NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_request ADD has_tools BOOLEAN NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_request ADD title VARCHAR(255) NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_request ADD preferred_garden_interaction_mode VARCHAR(30) NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_request ADD supports_local_food_security BOOLEAN NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_request ADD sharing_conditions TEXT DEFAULT NULL
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            DROP TABLE address
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land DROP CONSTRAINT FK_A800D5D8F5B7AF75
        SQL);
        $this->addSql(<<<'SQL'
            DROP INDEX UNIQ_A800D5D8F5B7AF75
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land DROP address_id
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_proposal ADD gardening_preference VARCHAR(255) NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_proposal DROP preferred_garden_interaction_mode
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_proposal DROP sharing_conditions
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_proposal ALTER soil_type TYPE VARCHAR(255)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_proposal ALTER orientation TYPE VARCHAR(255)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_proposal ALTER gardening_level TYPE VARCHAR(255)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_proposal ALTER looking_for_gardener_level TYPE VARCHAR(255)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_request DROP minimum_surface_wanted
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_request DROP gardening_level
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_request DROP has_tools
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_request DROP title
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_request DROP preferred_garden_interaction_mode
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_request DROP supports_local_food_security
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_request DROP sharing_conditions
        SQL);
    }
}
