<?php

declare(strict_types=1);

namespace DoctrineDefaultMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250123082725 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE land (name VARCHAR(255) NOT NULL, kind VARCHAR(150) DEFAULT \'individual\' NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A800D5D8C288C859 ON land (ulid)');
        $this->addSql('CREATE TABLE land_area (name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, land_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_446006A1C288C859 ON land_area (ulid)');
        $this->addSql('CREATE INDEX IDX_446006A11994904A ON land_area (land_id)');
        $this->addSql('CREATE TABLE land_area_parameter (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, above_ground BOOLEAN NOT NULL, land_area_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3224D9B9A51334FD ON land_area_parameter (land_area_id)');
        $this->addSql('CREATE TABLE land_area_setting (rotation_activated BOOLEAN NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, land_area_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4B8C7A1EC288C859 ON land_area_setting (ulid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4B8C7A1EA51334FD ON land_area_setting (land_area_id)');
        $this->addSql('CREATE TABLE land_member (joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner BOOLEAN NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, land_id INT NOT NULL, person_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DBD7ECAFC288C859 ON land_member (ulid)');
        $this->addSql('CREATE INDEX IDX_DBD7ECAF1994904A ON land_member (land_id)');
        $this->addSql('CREATE INDEX IDX_DBD7ECAF217BBB47 ON land_member (person_id)');
        $this->addSql('CREATE TABLE land_member_invitation (email VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, land_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F61C7411C288C859 ON land_member_invitation (ulid)');
        $this->addSql('CREATE INDEX IDX_F61C74111994904A ON land_member_invitation (land_id)');
        $this->addSql('CREATE TABLE land_member_setting (email_notification_activated BOOLEAN NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, land_member_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AD4F0279C288C859 ON land_member_setting (ulid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AD4F02795E192421 ON land_member_setting (land_member_id)');
        $this->addSql('CREATE TABLE land_research_deal (state VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_714E71D9C288C859 ON land_research_deal (ulid)');
        $this->addSql('CREATE TABLE land_research_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, person_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8EC04344C288C859 ON land_research_request (ulid)');
        $this->addSql('CREATE INDEX IDX_8EC04344217BBB47 ON land_research_request (person_id)');
        $this->addSql('CREATE TABLE land_role (name VARCHAR(255) NOT NULL, can_invite_someone BOOLEAN NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, position INT NOT NULL, land_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C49DB1A3C288C859 ON land_role (ulid)');
        $this->addSql('CREATE INDEX IDX_C49DB1A31994904A ON land_role (land_id)');
        $this->addSql('CREATE TABLE land_setting (looking_for_member BOOLEAN NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, land_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8768CCF9C288C859 ON land_setting (ulid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8768CCF91994904A ON land_setting (land_id)');
        $this->addSql('CREATE TABLE land_task (title VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, land_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C18AE0ECC288C859 ON land_task (ulid)');
        $this->addSql('CREATE INDEX IDX_C18AE0EC1994904A ON land_task (land_id)');
        $this->addSql('CREATE TABLE person (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, auth_id VARCHAR(180) NOT NULL, roles JSON NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_AUTH_ID ON person (auth_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE land_area ADD CONSTRAINT FK_446006A11994904A FOREIGN KEY (land_id) REFERENCES land (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_area_parameter ADD CONSTRAINT FK_3224D9B9A51334FD FOREIGN KEY (land_area_id) REFERENCES land_area (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_area_setting ADD CONSTRAINT FK_4B8C7A1EA51334FD FOREIGN KEY (land_area_id) REFERENCES land_area (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_member ADD CONSTRAINT FK_DBD7ECAF1994904A FOREIGN KEY (land_id) REFERENCES land (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_member ADD CONSTRAINT FK_DBD7ECAF217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_member_invitation ADD CONSTRAINT FK_F61C74111994904A FOREIGN KEY (land_id) REFERENCES land (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_member_setting ADD CONSTRAINT FK_AD4F02795E192421 FOREIGN KEY (land_member_id) REFERENCES land_member (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_research_request ADD CONSTRAINT FK_8EC04344217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_role ADD CONSTRAINT FK_C49DB1A31994904A FOREIGN KEY (land_id) REFERENCES land (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_setting ADD CONSTRAINT FK_8768CCF91994904A FOREIGN KEY (land_id) REFERENCES land (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_task ADD CONSTRAINT FK_C18AE0EC1994904A FOREIGN KEY (land_id) REFERENCES land (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE land_area DROP CONSTRAINT FK_446006A11994904A');
        $this->addSql('ALTER TABLE land_area_parameter DROP CONSTRAINT FK_3224D9B9A51334FD');
        $this->addSql('ALTER TABLE land_area_setting DROP CONSTRAINT FK_4B8C7A1EA51334FD');
        $this->addSql('ALTER TABLE land_member DROP CONSTRAINT FK_DBD7ECAF1994904A');
        $this->addSql('ALTER TABLE land_member DROP CONSTRAINT FK_DBD7ECAF217BBB47');
        $this->addSql('ALTER TABLE land_member_invitation DROP CONSTRAINT FK_F61C74111994904A');
        $this->addSql('ALTER TABLE land_member_setting DROP CONSTRAINT FK_AD4F02795E192421');
        $this->addSql('ALTER TABLE land_research_request DROP CONSTRAINT FK_8EC04344217BBB47');
        $this->addSql('ALTER TABLE land_role DROP CONSTRAINT FK_C49DB1A31994904A');
        $this->addSql('ALTER TABLE land_setting DROP CONSTRAINT FK_8768CCF91994904A');
        $this->addSql('ALTER TABLE land_task DROP CONSTRAINT FK_C18AE0EC1994904A');
        $this->addSql('DROP TABLE land');
        $this->addSql('DROP TABLE land_area');
        $this->addSql('DROP TABLE land_area_parameter');
        $this->addSql('DROP TABLE land_area_setting');
        $this->addSql('DROP TABLE land_member');
        $this->addSql('DROP TABLE land_member_invitation');
        $this->addSql('DROP TABLE land_member_setting');
        $this->addSql('DROP TABLE land_research_deal');
        $this->addSql('DROP TABLE land_research_request');
        $this->addSql('DROP TABLE land_role');
        $this->addSql('DROP TABLE land_setting');
        $this->addSql('DROP TABLE land_task');
        $this->addSql('DROP TABLE person');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
