<?php

declare(strict_types=1);

namespace DoctrineDefaultMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250803102432 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE plant_conversion_request DROP CONSTRAINT fk_cbeb65f6e406f3a2');
        $this->addSql('ALTER TABLE plant_conversion_request DROP CONSTRAINT fk_cbeb65f6b925ed19');
        $this->addSql('ALTER TABLE plant_custom DROP CONSTRAINT fk_1614c710217bbb47');
        $this->addSql('ALTER TABLE plant_custom DROP CONSTRAINT fk_1614c710bf396750');
        $this->addSql('ALTER TABLE plant_global DROP CONSTRAINT fk_b955a08bf396750');
        $this->addSql('ALTER TABLE land_cultivation_plan DROP CONSTRAINT fk_cf8a64a31d935652');
        $this->addSql('DROP INDEX idx_cf8a64a31d935652');
        $this->addSql('ALTER TABLE land_cultivation_plan DROP plant_id');
        $this->addSql('ALTER TABLE seed_stock_entry DROP CONSTRAINT fk_3fc1134a1d935652');
        $this->addSql('DROP INDEX idx_3fc1134a1d935652');
        $this->addSql('ALTER TABLE seed_stock_entry DROP plant_id');
        $this->addSql('DROP TABLE plant CASCADE');
        $this->addSql('DROP TABLE plant_conversion_request CASCADE');
        $this->addSql('DROP TABLE plant_custom CASCADE');
        $this->addSql('DROP TABLE plant_global CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE plant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, name VARCHAR(255) NOT NULL, latin_name VARCHAR(255) DEFAULT NULL, perpetual BOOLEAN NOT NULL, days_to_germination_average INT DEFAULT NULL, variety VARCHAR(255) DEFAULT NULL, sowing_minimal_temperature INT DEFAULT NULL, sowing_optimal_temperature INT DEFAULT NULL, sowing_months JSONB DEFAULT NULL, harvesting_months JSONB DEFAULT NULL, bio BOOLEAN NOT NULL, maturity VARCHAR(255) NOT NULL, soil_type VARCHAR(255) DEFAULT NULL, exposure VARCHAR(255) DEFAULT NULL, vegetation_threshold INT DEFAULT NULL, days_to_harvest_min INT DEFAULT NULL, days_to_harvest_max INT DEFAULT NULL, species VARCHAR(255) DEFAULT NULL, family JSONB DEFAULT NULL, planting_spacing_in_cm INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, kind VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_ab030d72c288c859 ON plant (ulid)');
        $this->addSql('CREATE TABLE plant_conversion_request (state VARCHAR(255) NOT NULL, message TEXT DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, plant_custom_id INT NOT NULL, merge_candidate_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_cbeb65f6b925ed19 ON plant_conversion_request (merge_candidate_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_cbeb65f6c288c859 ON plant_conversion_request (ulid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_cbeb65f6e406f3a2 ON plant_conversion_request (plant_custom_id)');
        $this->addSql('CREATE TABLE plant_custom (person_id INT NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_1614c710217bbb47 ON plant_custom (person_id)');
        $this->addSql('CREATE TABLE plant_global (id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE plant_conversion_request ADD CONSTRAINT fk_cbeb65f6e406f3a2 FOREIGN KEY (plant_custom_id) REFERENCES plant_custom (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE plant_conversion_request ADD CONSTRAINT fk_cbeb65f6b925ed19 FOREIGN KEY (merge_candidate_id) REFERENCES plant_global (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE plant_custom ADD CONSTRAINT fk_1614c710217bbb47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE plant_custom ADD CONSTRAINT fk_1614c710bf396750 FOREIGN KEY (id) REFERENCES plant (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE plant_global ADD CONSTRAINT fk_b955a08bf396750 FOREIGN KEY (id) REFERENCES plant (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_cultivation_plan ADD plant_id INT NOT NULL');
        $this->addSql('ALTER TABLE land_cultivation_plan ADD CONSTRAINT fk_cf8a64a31d935652 FOREIGN KEY (plant_id) REFERENCES plant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_cf8a64a31d935652 ON land_cultivation_plan (plant_id)');
        $this->addSql('ALTER TABLE seed_stock_entry ADD plant_id INT NOT NULL');
        $this->addSql('ALTER TABLE seed_stock_entry ADD CONSTRAINT fk_3fc1134a1d935652 FOREIGN KEY (plant_id) REFERENCES plant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_3fc1134a1d935652 ON seed_stock_entry (plant_id)');
    }
}
