<?php

declare(strict_types=1);

namespace DoctrineDefaultMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250414143611 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE land_api_key (permissions JSONB DEFAULT NULL, last_used_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, name VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, land_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_D10E99FCC288C859 ON land_api_key (ulid)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_D10E99FC1994904A ON land_api_key (land_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE person_api_key (permissions JSONB DEFAULT NULL, last_used_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, name VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, person_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_EB8C5E14C288C859 ON person_api_key (ulid)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_EB8C5E14217BBB47 ON person_api_key (person_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE land_api_key ADD CONSTRAINT FK_D10E99FC1994904A FOREIGN KEY (land_id) REFERENCES land (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE person_api_key ADD CONSTRAINT FK_EB8C5E14217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE land_api_key DROP CONSTRAINT FK_D10E99FC1994904A
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE person_api_key DROP CONSTRAINT FK_EB8C5E14217BBB47
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE land_api_key
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE person_api_key
        SQL);
    }
}
