<?php

declare(strict_types=1);

namespace DoctrineDefaultMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250222064704 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE land (name VARCHAR(255) NOT NULL, kind VARCHAR(150) DEFAULT \'individual\' NOT NULL, surface INT DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, default_role_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A800D5D8C288C859 ON land (ulid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A800D5D8248673E9 ON land (default_role_id)');
        $this->addSql('CREATE TABLE land_area (name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, state VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, land_id INT NOT NULL, land_greenhouse_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_446006A1C288C859 ON land_area (ulid)');
        $this->addSql('CREATE INDEX IDX_446006A11994904A ON land_area (land_id)');
        $this->addSql('CREATE INDEX IDX_446006A1FFFC30F4 ON land_area (land_greenhouse_id)');
        $this->addSql('CREATE TABLE land_area_parameter (above_ground BOOLEAN NOT NULL, width INT DEFAULT NULL, length INT DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, land_area_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3224D9B9C288C859 ON land_area_parameter (ulid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3224D9B9A51334FD ON land_area_parameter (land_area_id)');
        $this->addSql('CREATE TABLE land_area_setting (rotation_activated BOOLEAN NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, land_area_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4B8C7A1EC288C859 ON land_area_setting (ulid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4B8C7A1EA51334FD ON land_area_setting (land_area_id)');
        $this->addSql('CREATE TABLE land_cultivation_plan (start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expected_sowing_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, sowing_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expected_planting_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, planting_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expected_harvesting_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, harvesting_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, forecasted_end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, state VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, plant_id INT NOT NULL, land_id INT NOT NULL, land_area_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CF8A64A3C288C859 ON land_cultivation_plan (ulid)');
        $this->addSql('CREATE INDEX IDX_CF8A64A31D935652 ON land_cultivation_plan (plant_id)');
        $this->addSql('CREATE INDEX IDX_CF8A64A31994904A ON land_cultivation_plan (land_id)');
        $this->addSql('CREATE INDEX IDX_CF8A64A3A51334FD ON land_cultivation_plan (land_area_id)');
        $this->addSql('CREATE TABLE land_greenhouse (name VARCHAR(255) NOT NULL, construction_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CA2FB0A9C288C859 ON land_greenhouse (ulid)');
        $this->addSql('CREATE TABLE land_member (joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner BOOLEAN NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, land_id INT NOT NULL, person_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DBD7ECAFC288C859 ON land_member (ulid)');
        $this->addSql('CREATE INDEX IDX_DBD7ECAF1994904A ON land_member (land_id)');
        $this->addSql('CREATE INDEX IDX_DBD7ECAF217BBB47 ON land_member (person_id)');
        $this->addSql('CREATE TABLE land_member_land_role (land_member_id INT NOT NULL, land_role_id INT NOT NULL, PRIMARY KEY(land_member_id, land_role_id))');
        $this->addSql('CREATE INDEX IDX_A84C1BA75E192421 ON land_member_land_role (land_member_id)');
        $this->addSql('CREATE INDEX IDX_A84C1BA7CE1F56CD ON land_member_land_role (land_role_id)');
        $this->addSql('CREATE TABLE land_member_invitation (email VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, land_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F61C7411C288C859 ON land_member_invitation (ulid)');
        $this->addSql('CREATE INDEX IDX_F61C74111994904A ON land_member_invitation (land_id)');
        $this->addSql('CREATE TABLE land_member_setting (email_notification_activated BOOLEAN NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, land_member_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AD4F0279C288C859 ON land_member_setting (ulid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AD4F02795E192421 ON land_member_setting (land_member_id)');
        $this->addSql('CREATE TABLE land_research_deal (state VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_714E71D9C288C859 ON land_research_deal (ulid)');
        $this->addSql('CREATE TABLE land_research_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, person_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8EC04344C288C859 ON land_research_request (ulid)');
        $this->addSql('CREATE INDEX IDX_8EC04344217BBB47 ON land_research_request (person_id)');
        $this->addSql('CREATE TABLE land_role (name VARCHAR(255) NOT NULL, permissions JSONB DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, position INT NOT NULL, land_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C49DB1A3C288C859 ON land_role (ulid)');
        $this->addSql('CREATE INDEX IDX_C49DB1A31994904A ON land_role (land_id)');
        $this->addSql('CREATE TABLE land_setting (looking_for_member BOOLEAN NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, land_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8768CCF9C288C859 ON land_setting (ulid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8768CCF91994904A ON land_setting (land_id)');
        $this->addSql('CREATE TABLE land_task (title VARCHAR(255) NOT NULL, content JSON DEFAULT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, land_id INT NOT NULL, land_area_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C18AE0ECC288C859 ON land_task (ulid)');
        $this->addSql('CREATE INDEX IDX_C18AE0EC1994904A ON land_task (land_id)');
        $this->addSql('CREATE INDEX IDX_C18AE0ECA51334FD ON land_task (land_area_id)');
        $this->addSql('CREATE TABLE person (auth_id VARCHAR(180) NOT NULL, roles JSON NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) DEFAULT NULL, given_name VARCHAR(255) DEFAULT NULL, family_name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_AUTH_ID ON person (auth_id)');
        $this->addSql('CREATE TABLE plant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, name VARCHAR(255) NOT NULL, latin_name VARCHAR(255) DEFAULT NULL, perpetual BOOLEAN NOT NULL, days_to_germination_average INT DEFAULT NULL, variety VARCHAR(255) DEFAULT NULL, sowing_minimal_temperature INT DEFAULT NULL, sowing_optimal_temperature INT DEFAULT NULL, sowing_months JSONB DEFAULT NULL, harvesting_months JSONB DEFAULT NULL, bio BOOLEAN NOT NULL, maturity VARCHAR(255) NOT NULL, soil_type VARCHAR(255) DEFAULT NULL, exposure VARCHAR(255) DEFAULT NULL, vegetation_threshold INT DEFAULT NULL, days_to_harvest_min INT DEFAULT NULL, days_to_harvest_max INT DEFAULT NULL, species VARCHAR(255) DEFAULT NULL, family JSONB DEFAULT NULL, planting_spacing_in_cm INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, kind VARCHAR(255) NOT NULL, shared BOOLEAN DEFAULT NULL, person_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AB030D72C288C859 ON plant (ulid)');
        $this->addSql('CREATE INDEX IDX_AB030D72217BBB47 ON plant (person_id)');
        $this->addSql('CREATE TABLE seed_stock (name VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, person_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7F3E4F70C288C859 ON seed_stock (ulid)');
        $this->addSql('CREATE INDEX IDX_7F3E4F70217BBB47 ON seed_stock (person_id)');
        $this->addSql('CREATE TABLE seed_stock_entry (quantity_in_gram INT DEFAULT NULL, quantity_in_number_of_seed INT DEFAULT NULL, purchase_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, publicly_shared BOOLEAN NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, seed_stock_id INT NOT NULL, plant_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3FC1134AC288C859 ON seed_stock_entry (ulid)');
        $this->addSql('CREATE INDEX IDX_3FC1134A8430E37E ON seed_stock_entry (seed_stock_id)');
        $this->addSql('CREATE INDEX IDX_3FC1134A1D935652 ON seed_stock_entry (plant_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE land ADD CONSTRAINT FK_A800D5D8248673E9 FOREIGN KEY (default_role_id) REFERENCES land_role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_area ADD CONSTRAINT FK_446006A11994904A FOREIGN KEY (land_id) REFERENCES land (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_area ADD CONSTRAINT FK_446006A1FFFC30F4 FOREIGN KEY (land_greenhouse_id) REFERENCES land_greenhouse (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_area_parameter ADD CONSTRAINT FK_3224D9B9A51334FD FOREIGN KEY (land_area_id) REFERENCES land_area (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_area_setting ADD CONSTRAINT FK_4B8C7A1EA51334FD FOREIGN KEY (land_area_id) REFERENCES land_area (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_cultivation_plan ADD CONSTRAINT FK_CF8A64A31D935652 FOREIGN KEY (plant_id) REFERENCES plant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_cultivation_plan ADD CONSTRAINT FK_CF8A64A31994904A FOREIGN KEY (land_id) REFERENCES land (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_cultivation_plan ADD CONSTRAINT FK_CF8A64A3A51334FD FOREIGN KEY (land_area_id) REFERENCES land_area (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_member ADD CONSTRAINT FK_DBD7ECAF1994904A FOREIGN KEY (land_id) REFERENCES land (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_member ADD CONSTRAINT FK_DBD7ECAF217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_member_land_role ADD CONSTRAINT FK_A84C1BA75E192421 FOREIGN KEY (land_member_id) REFERENCES land_member (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_member_land_role ADD CONSTRAINT FK_A84C1BA7CE1F56CD FOREIGN KEY (land_role_id) REFERENCES land_role (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_member_invitation ADD CONSTRAINT FK_F61C74111994904A FOREIGN KEY (land_id) REFERENCES land (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_member_setting ADD CONSTRAINT FK_AD4F02795E192421 FOREIGN KEY (land_member_id) REFERENCES land_member (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_research_request ADD CONSTRAINT FK_8EC04344217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_role ADD CONSTRAINT FK_C49DB1A31994904A FOREIGN KEY (land_id) REFERENCES land (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_setting ADD CONSTRAINT FK_8768CCF91994904A FOREIGN KEY (land_id) REFERENCES land (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_task ADD CONSTRAINT FK_C18AE0EC1994904A FOREIGN KEY (land_id) REFERENCES land (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_task ADD CONSTRAINT FK_C18AE0ECA51334FD FOREIGN KEY (land_area_id) REFERENCES land_area (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE plant ADD CONSTRAINT FK_AB030D72217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE seed_stock ADD CONSTRAINT FK_7F3E4F70217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE seed_stock_entry ADD CONSTRAINT FK_3FC1134A8430E37E FOREIGN KEY (seed_stock_id) REFERENCES seed_stock (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE seed_stock_entry ADD CONSTRAINT FK_3FC1134A1D935652 FOREIGN KEY (plant_id) REFERENCES plant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE land DROP CONSTRAINT FK_A800D5D8248673E9');
        $this->addSql('ALTER TABLE land_area DROP CONSTRAINT FK_446006A11994904A');
        $this->addSql('ALTER TABLE land_area DROP CONSTRAINT FK_446006A1FFFC30F4');
        $this->addSql('ALTER TABLE land_area_parameter DROP CONSTRAINT FK_3224D9B9A51334FD');
        $this->addSql('ALTER TABLE land_area_setting DROP CONSTRAINT FK_4B8C7A1EA51334FD');
        $this->addSql('ALTER TABLE land_cultivation_plan DROP CONSTRAINT FK_CF8A64A31D935652');
        $this->addSql('ALTER TABLE land_cultivation_plan DROP CONSTRAINT FK_CF8A64A31994904A');
        $this->addSql('ALTER TABLE land_cultivation_plan DROP CONSTRAINT FK_CF8A64A3A51334FD');
        $this->addSql('ALTER TABLE land_member DROP CONSTRAINT FK_DBD7ECAF1994904A');
        $this->addSql('ALTER TABLE land_member DROP CONSTRAINT FK_DBD7ECAF217BBB47');
        $this->addSql('ALTER TABLE land_member_land_role DROP CONSTRAINT FK_A84C1BA75E192421');
        $this->addSql('ALTER TABLE land_member_land_role DROP CONSTRAINT FK_A84C1BA7CE1F56CD');
        $this->addSql('ALTER TABLE land_member_invitation DROP CONSTRAINT FK_F61C74111994904A');
        $this->addSql('ALTER TABLE land_member_setting DROP CONSTRAINT FK_AD4F02795E192421');
        $this->addSql('ALTER TABLE land_research_request DROP CONSTRAINT FK_8EC04344217BBB47');
        $this->addSql('ALTER TABLE land_role DROP CONSTRAINT FK_C49DB1A31994904A');
        $this->addSql('ALTER TABLE land_setting DROP CONSTRAINT FK_8768CCF91994904A');
        $this->addSql('ALTER TABLE land_task DROP CONSTRAINT FK_C18AE0EC1994904A');
        $this->addSql('ALTER TABLE land_task DROP CONSTRAINT FK_C18AE0ECA51334FD');
        $this->addSql('ALTER TABLE plant DROP CONSTRAINT FK_AB030D72217BBB47');
        $this->addSql('ALTER TABLE seed_stock DROP CONSTRAINT FK_7F3E4F70217BBB47');
        $this->addSql('ALTER TABLE seed_stock_entry DROP CONSTRAINT FK_3FC1134A8430E37E');
        $this->addSql('ALTER TABLE seed_stock_entry DROP CONSTRAINT FK_3FC1134A1D935652');
        $this->addSql('DROP TABLE land');
        $this->addSql('DROP TABLE land_area');
        $this->addSql('DROP TABLE land_area_parameter');
        $this->addSql('DROP TABLE land_area_setting');
        $this->addSql('DROP TABLE land_cultivation_plan');
        $this->addSql('DROP TABLE land_greenhouse');
        $this->addSql('DROP TABLE land_member');
        $this->addSql('DROP TABLE land_member_land_role');
        $this->addSql('DROP TABLE land_member_invitation');
        $this->addSql('DROP TABLE land_member_setting');
        $this->addSql('DROP TABLE land_research_deal');
        $this->addSql('DROP TABLE land_research_request');
        $this->addSql('DROP TABLE land_role');
        $this->addSql('DROP TABLE land_setting');
        $this->addSql('DROP TABLE land_task');
        $this->addSql('DROP TABLE person');
        $this->addSql('DROP TABLE plant');
        $this->addSql('DROP TABLE seed_stock');
        $this->addSql('DROP TABLE seed_stock_entry');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
