<?php

declare(strict_types=1);

namespace DoctrineDefaultMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250228111939 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE land_greenhouse_parameter (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, land_greenhouse_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_321961B4C288C859 ON land_greenhouse_parameter (ulid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_321961B4FFFC30F4 ON land_greenhouse_parameter (land_greenhouse_id)');
        $this->addSql('CREATE TABLE land_greenhouse_setting (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ulid UUID NOT NULL, land_greenhouse_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2B14AD7BC288C859 ON land_greenhouse_setting (ulid)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2B14AD7BFFFC30F4 ON land_greenhouse_setting (land_greenhouse_id)');
        $this->addSql('ALTER TABLE land_greenhouse_parameter ADD CONSTRAINT FK_321961B4FFFC30F4 FOREIGN KEY (land_greenhouse_id) REFERENCES land_greenhouse (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_greenhouse_setting ADD CONSTRAINT FK_2B14AD7BFFFC30F4 FOREIGN KEY (land_greenhouse_id) REFERENCES land_greenhouse (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE land_cultivation_plan ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE land_cultivation_plan ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE land_member_invitation ADD state VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE land_member_invitation ADD accepted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE land_member_invitation ADD refused_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE land_member_invitation ADD person_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE land_member_invitation ADD CONSTRAINT FK_F61C7411217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX IDX_F61C7411217BBB47 ON land_member_invitation (person_id)');
        $this->addSql('ALTER TABLE land_task ADD state VARCHAR(255) NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE land_greenhouse_parameter DROP CONSTRAINT FK_321961B4FFFC30F4');
        $this->addSql('ALTER TABLE land_greenhouse_setting DROP CONSTRAINT FK_2B14AD7BFFFC30F4');
        $this->addSql('DROP TABLE land_greenhouse_parameter');
        $this->addSql('DROP TABLE land_greenhouse_setting');
        $this->addSql('ALTER TABLE land_cultivation_plan DROP created_at');
        $this->addSql('ALTER TABLE land_cultivation_plan DROP updated_at');
        $this->addSql('ALTER TABLE land_task DROP state');
        $this->addSql('ALTER TABLE land_member_invitation DROP CONSTRAINT FK_F61C7411217BBB47');
        $this->addSql('DROP INDEX IDX_F61C7411217BBB47');
        $this->addSql('ALTER TABLE land_member_invitation DROP state');
        $this->addSql('ALTER TABLE land_member_invitation DROP accepted_at');
        $this->addSql('ALTER TABLE land_member_invitation DROP refused_at');
        $this->addSql('ALTER TABLE land_member_invitation DROP person_id');
    }
}
