framework:
  annotations:
    enabled: false
  disallow_search_engine_index: true
  handle_all_throwables: true
  http_method_override: false
  php_errors:
    log: true
  secret: '%env(APP_SECRET)%'
  trusted_proxies: '127.0.0.1,REMOTE_ADDR'
  validation:
    email_validation_mode: strict

when@test:
  framework:
    test:
      true
      #session:
    #storage_factory_id: session.storage.factory.mock_file
