framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    failure_transport: failed
    transports:
      async: '%env(MESSENGER_TRANSPORT_DSN)%/async'
      failed: 'doctrine://default?queue_name=failed'
      sync: 'sync://'

    #buses:
    #messenger.bus.default:
    #middleware:
    #- App\Scheduler\Scheduler

when@test:
  framework:
    messenger:
      transports:
        failed: '%env(MESSENGER_TRANSPORT_DSN)%/failed'
        sync: '%env(MESSENGER_TRANSPORT_DSN)%/sync'
