security:
  access_decision_manager:
    strategy: unanimous
    allow_if_all_abstain: false

  access_control:
    - { path: ^/api/docs, roles: PUBLIC_ACCESS }
    - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      custom_authenticators:
        - Lychen\UtilZitadelBundle\Authenticator\ZitadelUserAuthenticator
        - App\Security\Authenticator\PersonApiKeyAuthenticator
      lazy: true
      pattern: ^/
      provider: all_users
      stateless: true

  providers:
    zitadel_user_provider:
      id: Lychen\UtilZitadelBundle\UserProvider\ZitadelUserProvider
    person_api_key:
      entity:
        class: App\Entity\PersonApiKey
        property: jti
    all_users:
      chain:
        providers: [ 'person_api_key', 'zitadel_user_provider' ]
