export const colorsConfig = {
  primary: {
    DEFAULT: 'rgb(var(--color-primary))',
    on: 'rgb(var(--color-on-primary))',
    container: 'rgb(var(--color-primary-container))',
    'container-on': 'rgb(var(--color-on-primary-container))',
  },
  secondary: {
    DEFAULT: 'rgb(var(--color-secondary))',
    on: 'rgb(var(--color-on-secondary))',
    container: 'rgb(var(--color-secondary-container))',
    'container-on': 'rgb(var(--color-on-secondary-container))',
  },
  tertiary: {
    DEFAULT: 'rgb(var(--color-tertiary))',
    on: 'rgb(var(--color-on-tertiary))',
    container: 'rgb(var(--color-tertiary-container))',
    'container-on': 'rgb(var(--color-on-tertiary-container))',
  },
  positive: {
    DEFAULT: 'rgb(var(--color-positive))',
    on: 'rgb(var(--color-on-positive))',
    container: 'rgb(var(--color-positive-container))',
    'container-on': 'rgb(var(--color-on-positive-container))',
  },
  warning: {
    DEFAULT: 'rgb(var(--color-warning))',
    on: 'rgb(var(--color-on-warning))',
    container: 'rgb(var(--color-warning-container))',
    'container-on': 'rgb(var(--color-on-warning-container))',
  },
  negative: {
    DEFAULT: 'rgb(var(--color-negative))',
    on: 'rgb(var(--color-on-negative))',
    container: 'rgb(var(--color-negative-container))',
    'container-on': 'rgb(var(--color-on-negative-container))',
  },
  surface: {
    DEFAULT: 'rgb(var(--color-surface))',
    on: 'rgb(var(--color-on-surface))',
    dim: 'rgb(var(--color-surface-dim))',
    'dim-on': 'rgb(var(--color-on-surface-dim))',
    bright: 'rgb(var(--color-surface-bright))',
    'bright-on': 'rgb(var(--color-on-surface-bright))',
    variant: 'rgb(var(--color-surface-variant))',
    'variant-on': 'rgb(var(--color-on-surface-variant))',
    container: 'rgb(var(--color-surface-container))',
    'container-on': 'rgb(var(--color-on-surface-container))',
    'container-low': 'rgb(var(--color-surface-container-low))',
    'container-low-on': 'rgb(var(--color-on-surface-container-low))',
    'container-lowest': 'rgb(var(--color-surface-container-lowest))',
    'container-lowest-on': 'rgb(var(--color-on-surface-container-lowest))',
    'container-high': 'rgb(var(--color-surface-container-high))',
    'container-high-on': 'rgb(var(--color-on-surface-container-high))',
    'container-highest': 'rgb(var(--color-surface-container-highest))',
    'container-highest-on': 'rgb(var(--color-on-surface-container-highest))',
  },
};
