services:
  website:
    image: ghcr.io/alpsify/lychen/staging/humu/website:latest
    labels:
      - traefik.http.routers.lychen-staging-humu-website-mzu8rl-73-websecure.middlewares=ip-allow@file
    restart: unless-stopped
