name: 'Deploy to staging'

env:
  FONTAWESOME_PACKAGE_TOKEN: ${{ secrets.FONTAWESOME_PACKAGE_TOKEN }}
  REGISTRY: ghcr.io

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  #  define-projects:
  #    runs-on: ubuntu-latest
  #    outputs:
  #      projects: ${{ steps.projects.outputs.projects }}
  #
  #    steps:
  #      - name: Define Projects
  #        id: projects
  #        run: |
  #          echo 'colors=["red", "green", "blue"]' >> "$GITHUB_OUTPUT"

  buildandpush:
    name: 'Build and push docker images'
    strategy:
      matrix:
        projects:
          [
            'eko-website ',
            'humu-website ',
            'kiro-admin-app ',
            'kiro-manager-app ',
            'kiro-member-app ',
            'kiro-producer-app ',
            'kiro-website ',
            'kolo-website ',
            'luna-website ',
            'meli-website ',
            'myko-website ',
            'novi-website ',
            'tera-api ',
            'tera-app ',
            'tera-website ',
            'vara-website ',
            'website ',
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - name: Set up Moon Toolchain
        uses: 'moonrepo/setup-toolchain@v0'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        platforms: linux/amd64,linux/arm64
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: 'moon ci ${{ matrix.projects }}:staging-docker-push'

  deploy:
    name: 'Deploy to VPS'
    runs-on: ubuntu-latest
    needs: buildandpush
    strategy:
      matrix:
        projects:
          [
            'eko-website ',
            'humu-website ',
            'kiro-admin-app ',
            'kiro-manager-app ',
            'kiro-member-app ',
            'kiro-producer-app ',
            'kiro-website ',
            'kolo-website ',
            'luna-website ',
            'meli-website ',
            'myko-website ',
            'novi-website ',
            'tera-api ',
            'tera-app ',
            'tera-website ',
            'vara-website ',
            'website ',
          ]
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - name: Set up Moon Toolchain
        uses: 'moonrepo/setup-toolchain@v0'
      - name: 'Redeploy from Dokploy on VPS'
        env:
          DOKPLOY_API_TOKEN: ${{ secrets.DOKPLOY_API_TOKEN }}
          DOKPLOY_API_URL: ${{ secrets.DOKPLOY_API_URL }}
        run: 'moon ci :staging-dokploy-compose-deploy'
