name: 'Playwright tests'

env:
  FONTAWESOME_PACKAGE_TOKEN: ${{ secrets.FONTAWESOME_PACKAGE_TOKEN }}

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  define-matrix:
    name: 'Gather affected projects'
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.projects.outputs.projects }}
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - name: Set up Moon Toolchain
        uses: 'moonrepo/setup-toolchain@v0'
      - run: moon query projects --tags vue --affected --downstream deep
      - name: Define Projects
        id: projects
        run: |
          echo "projects=$(moon query projects --tags playwright --affected --downstream deep --json | jq -r '.projects | map(.id | @json) | join(",")' | sed 's/^/\[/; s/$/\]/')" >> "$GITHUB_OUTPUT"
      - run: echo ${{ steps.projects.outputs.projects }}

  test:
    timeout-minutes: 60
    if: ${{ needs.define-matrix.outputs.projects != '[]' && needs.define-matrix.outputs.projects != '' }}
    name: '${{ matrix.projects }} | Playwright run'
    needs: define-matrix
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        projects: ${{ fromJSON(needs.define-matrix.outputs.projects) }}
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - name: Set up Moon Toolchain
        uses: 'moonrepo/setup-toolchain@v0'
        with:
          auto-install: true
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Add local domain to /etc/hosts
        run: echo "127.0.0.1 app.tera.lychen.local" | sudo tee -a /etc/hosts
      - name: Run tests
        run: moon ci tera-tests-app:run
