name: CI/CD Symfony projects

env:
  REGISTRY: ghcr.io/alpsify/lychen/test

on:
  pull_request:
  workflow_dispatch: {} # Permet d’exécuter manuellement les jobs de déploiement

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  define-matrix:
    name: 'Gather affected projects'
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.projects.outputs.projects }}
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - name: Set up Moon Toolchain
        uses: 'moonrepo/setup-toolchain@v0'
      - name: Define Projects
        id: projects
        run: |
          echo "projects=$(moon query projects --tags symfony --affected --downstream deep | awk 'NR % 2 == 1 {print "\"" $1 "\""}' | paste -sd, - | sed 's/^/\[/; s/$/\]/')" >> "$GITHUB_OUTPUT"
      - run: echo ${{ steps.projects.outputs.projects }}

  build-and-push-test-image:
    if: ${{ needs.define-matrix.outputs.projects != '[]' && needs.define-matrix.outputs.projects != '' }}
    name: '${{ matrix.projects }} | Build docker test image'
    needs: define-matrix
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        projects: ${{ fromJSON(needs.define-matrix.outputs.projects) }}
    outputs:
      matrix_test_image_name: ${{ steps.set-image.outputs.matrix_image_names }}
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0

      - name: Set up Moon Toolchain
        uses: 'moonrepo/setup-toolchain@v0'
        with:
          auto-install: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate IMAGE_NAME
        id: set-image
        run: |
          # Set for current job
          echo "TEST_IMAGE_NAME=${{ env.REGISTRY }}/${{ matrix.projects }}" >> $GITHUB_ENV
          # Set for other jobs
          echo "matrix_image_names=${{ env.REGISTRY }}/${{ matrix.projects }}" >> $GITHUB_OUTPUT

      - name: Pull test image if exists
        run: docker pull ${{ env.TEST_IMAGE_NAME }}:latest || true

      - name: Build docker test image
        run: moon ci ${{ matrix.projects }}:ci-test-build-docker-image

      - name: Push docker test image
        run: |
          docker push ${{ env.TEST_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.TEST_IMAGE_NAME }}:latest

  install-vendors:
    name: '${{ matrix.projects }} | Install vendors'
    runs-on: ubuntu-latest
    needs:
      - define-matrix
      - build-and-push-test-image
    strategy:
      fail-fast: false
      matrix:
        projects: ${{ fromJSON(needs.define-matrix.outputs.projects) }}
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0

      - name: Set up Moon Toolchain
        uses: 'moonrepo/setup-toolchain@v0'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set IMAGE_NAME for this project
        run: echo "TEST_IMAGE_NAME=${{ needs.build-and-push-test-image.outputs.matrix_test_image_name }}" >> $GITHUB_ENV

      - name: Install vendors
        run: moon ci ${{ matrix.projects }}:ci-install-vendors

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: vendors-packages
          path: |
            vendor
            tools/vendor
            node_modules
            .cache

  lint-php:
    name: '${{ matrix.projects }} | Lint PHP files'
    needs:
      - define-matrix
      - build-and-push-test-image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projects: ${{ fromJSON(needs.define-matrix.outputs.projects) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Moon Toolchain
        uses: 'moonrepo/setup-toolchain@v0'

      - name: Set IMAGE_NAME for this project
        run: echo "TEST_IMAGE_NAME=${{ needs.build-and-push-test-image.outputs.matrix_test_image_name }}" >> $GITHUB_ENV

      - name: Install tools
        run: moon ci ${{ matrix.projects }}:ci-install-tools

      - name: Lint src folder
        run: moon ci ${{ matrix.projects }}:ci-php-cs-fixer-src

      - name: Lint test folder
        run: moon ci ${{ matrix.projects }}:ci-php-cs-fixer-test

  validate-db-schema:
    name: '${{ matrix.projects }} | Validate DB schema'
    needs:
      - define-matrix
      - build-and-push-test-image
      - install-vendors
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projects: ${{ fromJSON(needs.define-matrix.outputs.projects) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Moon Toolchain
        uses: 'moonrepo/setup-toolchain@v0'

      - name: Set IMAGE_NAME for this project
        run: echo "TEST_IMAGE_NAME=${{ needs.build-and-push-test-image.outputs.matrix_test_image_name }}" >> $GITHUB_ENV

      - name: Validate DB
        run: moon ci ${{ matrix.projects }}:ci-validate-db-schema

  check-vulnerabilities:
    name: '${{ matrix.projects }} | Check packages vulnerabilities'
    needs:
      - define-matrix
      - build-and-push-test-image
      - install-vendors
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projects: ${{ fromJSON(needs.define-matrix.outputs.projects) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Moon Toolchain
        uses: 'moonrepo/setup-toolchain@v0'

      - name: Set IMAGE_NAME for this project
        run: echo "TEST_IMAGE_NAME=${{ needs.build-and-push-test-image.outputs.matrix_test_image_name }}" >> $GITHUB_ENV

      - name: Check vulnerabilities
        run: moon ci ${{ matrix.projects }}:ci-check-vulnerabilities

  phpunit:
    name: '${{ matrix.projects }} | PHPUnit'
    needs:
      - define-matrix
      - build-and-push-test-image
      - install-vendors
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projects: ${{ fromJSON(needs.define-matrix.outputs.projects) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set IMAGE_NAME for this project
        run: echo "TEST_IMAGE_NAME=${{ needs.build-and-push-test-image.outputs.matrix_test_image_name }}" >> $GITHUB_ENV

      - name: Set up Moon Toolchain
        uses: 'moonrepo/setup-toolchain@v0'

      - name: Test
        run: moon ci ${{ matrix.projects }}:ci-test-phpunit tests/Functionnal
